# Generated by Django 6.0.2 on 2026-09-02 20:56

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Adres URL (slug)')),
                ('location', models.CharField(choices=[('polska', 'Polska'), ('teneryfa', 'Teneryfa')], max_length=20, verbose_name='Lokalizacja')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena (EUR)')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Powierzchnia (m²)')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Liczba pokoi')),
                ('status', models.CharField(choices=[('dostepny', 'Dostępny'), ('zarezerwowany', 'Zarezerwowany'), ('sprzedany', 'Sprzedany')], default='dostepny', max_length=20, verbose_name='Status')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Oferty',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.property_image_upload_to, verbose_name='Zdjęcie')),
                ('alt_text', models.CharField(max_length=250, verbose_name='Opis alternatywny (SEO)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Zdjęcie główne')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.property', verbose_name='Oferta')),
            ],
            options={
                'verbose_name': 'Zdjęcie oferty',
                'verbose_name_plural': 'Zdjęcia oferty',
                'ordering': ['order', 'id'],
            },
        ),
    ]
