# Generated by Django 6.0.2 on 2026-09-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Imię i nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres e-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Temat')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytana')),
            ],
            options={
                'verbose_name': 'Wiadomość kontaktowa',
                'verbose_name_plural': 'Wiadomości kontaktowe',
                'ordering': ['-created_at'],
            },
        ),
    ]
