# Generated by Django 6.0.2 on 2026-09-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adres / okolica'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, help_text='Każda linia to jeden punkt na liście udogodnień na stronie oferty.', verbose_name='Udogodnienia (jedno na linię)'),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Liczba łazienek'),
        ),
    ]
