# Generated by Django 6.0.2 on 2026-09-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_property_address_property_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='advantages',
            field=models.TextField(blank=True, help_text='Każda linia to jeden punkt na liście zalet na stronie oferty.', verbose_name='Zalety (jedna na linię)'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_details',
            field=models.TextField(blank=True, help_text='Rozbicie powierzchni, np. "43,8 m² salon + 25,6 m² taras". Liczba z pola wyżej i tak zawsze pokazuje się w zestawieniu parametrów.', verbose_name='Powierzchnia — opis'),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, help_text='Każda linia to jeden punkt na liście wyposażenia na stronie oferty.', verbose_name='Wyposażenie (jedno na linię)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis nieruchomości'),
        ),
    ]
