# Generated by Django 6.0.2 on 2026-09-08 19:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_advantages_property_area_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.gallery_photo_upload_to, verbose_name='Zdjęcie')),
                ('alt_text', models.CharField(max_length=250, verbose_name='Opis alternatywny (SEO)')),
                ('order', models.PositiveIntegerField(default=0, help_text='0 = duże zdjęcie, 1-4 = małe kafelki w siatce, wyższe = tylko w powiększeniu.', verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Zdjęcie galerii (strona główna)',
                'verbose_name_plural': 'Zdjęcia galerii (strona główna)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena (PLN)'),
        ),
    ]
