# Generated by Django 6.0.2 on 2026-09-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_galleryphoto_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN (zł)'), ('EUR', 'EUR (€)')], default='PLN', max_length=3, verbose_name='Waluta'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena'),
        ),
    ]
