# Generated by Django 6.0.2 on 2026-09-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_property_currency_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Możesz zostawić puste — zostanie dogenerowany automatycznie.', max_length=250, verbose_name='Opis alternatywny (SEO)'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Możesz zostawić puste — zostanie dogenerowany automatycznie.', max_length=250, verbose_name='Opis alternatywny (SEO)'),
        ),
    ]
