# Generated by Django 6.0.2 on 2026-09-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_galleryphoto_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Oferta', 'verbose_name_plural': 'Oferty'},
        ),
        migrations.AddField(
            model_name='property',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Mniejsza liczba = wyżej na liście ofert. Oferty z tą samą wartością sortują się po dacie dodania (najnowsze pierwsze).', verbose_name='Kolejność na stronie'),
        ),
    ]
